package org.sfml_dev.window;

import static org.sfml_dev.window.sys.SFML_Window.*;

public class Keyboard {
    
    public enum Key {
        A,
        B,
        C,
        D,
        E,
        F,
        G,
        H,
        I,
        J,
        K,
        L,
        M,
        N,
        O,
        P,
        Q,
        R,
        S,
        T,
        U,
        V,
        W,
        X,
        Y,
        Z,
        NUM_0,
        NUM_1,
        NUM_2,
        NUM_3,
        NUM_4,
        NUM_5,
        NUM_6,
        NUM_7,
        NUM_8,
        NUM_9,
        ESCAPE,
        L_CONTROL,
        L_SHIFT,
        L_ALT,
        L_SYSTEM,
        R_CONTROL,
        R_SHIFT,
        R_ALT,
        R_SYSTEM,
        MENU,
        L_BRACKET,
        R_BRACKET,
        SEMICOLON,
        COMMA,
        PERIOD,
        QUOTE,
        SLASH,
        BACKSLASH,
        TILDE,
        EQUAL,
        HYPHEN,
        SPACE,
        ENTER,
        BACKSPACE,
        TAB,
        PAGE_UP,
        PAGE_DOWN,
        END,
        HOME,
        INSERT,
        DELETE,
        ADD,
        SUBTRACT,
        MULTIPLY,
        DIVIDE,
        LEFT,
        RIGHT,
        UP,
        DOWN,
        NUMPAD_0,
        NUMPAD_1,
        NUMPAD_2,
        NUMPAD_3,
        NUMPAD_4,
        NUMPAD_5,
        NUMPAD_6,
        NUMPAD_7,
        NUMPAD_8,
        NUMPAD_9,
        F1,
        F2,
        F3,
        F4,
        F5,
        F6,
        F7,
        F8,
        F9,
        F10,
        F11,
        F12,
        F13,
        F14,
        F15,
        PAUSE,
        UNKNOWN,
    }

    private Keyboard() {}

    public static boolean isKeyPressed(Key key) {
        return sf_Keyboard_isKeyPressed(key == Key.UNKNOWN ? -1 : key.ordinal());
    }

    public static void setVirtualKeyboardVisible(boolean visible) {
        sf_Keyboard_setVirtualKeyboardVisible(visible);
    }
}
