/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sfml_dev_system_sys_jni */

#ifndef _Included_org_sfml_dev_system_sys_jni
#define _Included_org_sfml_dev_system_sys_jni
#ifdef __cplusplus
extern "C" {
#endif
#undef org_sfml_dev_system_sys_jni_JNI_COMMIT
#define org_sfml_dev_system_sys_jni_JNI_COMMIT 1L
#undef org_sfml_dev_system_sys_jni_JNI_ABORT
#define org_sfml_dev_system_sys_jni_JNI_ABORT 2L
/*
 * Class:     org_sfml_dev_system_sys_jni
 * Method:    NewString
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_sfml_1dev_system_sys_jni_NewString
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_sfml_dev_system_sys_jni
 * Method:    GetStringChars
 * Signature: (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_system_sys_jni_GetStringChars
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     org_sfml_dev_system_sys_jni
 * Method:    ReleaseStringChars
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_system_sys_jni_ReleaseStringChars
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     org_sfml_dev_system_sys_jni
 * Method:    GetByteArrayElements
 * Signature: ([BJ)J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_system_sys_jni_GetByteArrayElements
  (JNIEnv *, jclass, jbyteArray, jlong);

/*
 * Class:     org_sfml_dev_system_sys_jni
 * Method:    ReleaseByteArrayElements
 * Signature: ([BJI)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_system_sys_jni_ReleaseByteArrayElements
  (JNIEnv *, jclass, jbyteArray, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
