/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sfml_dev_system_sys_new_ */

#ifndef _Included_org_sfml_dev_system_sys_new_
#define _Included_org_sfml_dev_system_sys_new_
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_sfml_dev_system_sys_new_
 * Method:    operator_new
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_system_sys_new_1_operator_1new
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_system_sys_new_
 * Method:    operator_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_system_sys_new_1_operator_1delete
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
