/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sfml_dev_graphics_sys_SFML_Graphics */

#ifndef _Included_org_sfml_dev_graphics_sys_SFML_Graphics
#define _Included_org_sfml_dev_graphics_sys_SFML_Graphics
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Color_sizeof
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Color_1sizeof
  (JNIEnv *, jclass);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Color_Color
 * Signature: (JBBBB)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Color_1Color
  (JNIEnv *, jclass, jlong, jbyte, jbyte, jbyte, jbyte);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Color_getR
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Color_1getR
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Color_getG
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Color_1getG
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Color_getB
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Color_1getB
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Color_getA
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Color_1getA
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_FloatRect_sizeof
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1FloatRect_1sizeof
  (JNIEnv *, jclass);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_FloatRect_FloatRect
 * Signature: (JFFFF)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1FloatRect_1FloatRect
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_FloatRect_getLeft
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1FloatRect_1getLeft
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_FloatRect_getTop
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1FloatRect_1getTop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_FloatRect_getWidth
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1FloatRect_1getWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_FloatRect_getHeight
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1FloatRect_1getHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Transform_sizeof
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Transform_1sizeof
  (JNIEnv *, jclass);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Transform_Identity
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Transform_1Identity
  (JNIEnv *, jclass);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Transform_Transform
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Transform_1Transform__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Transform_Transform
 * Signature: (JFFFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Transform_1Transform__JFFFFFFFFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Transform_Transform
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Transform_1Transform__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Transform_getMatrix
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Transform_1getMatrix
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Transform_getInverse
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Transform_1getInverse
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Transform_transformPoint
 * Signature: (JJFF)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Transform_1transformPoint__JJFF
  (JNIEnv *, jclass, jlong, jlong, jfloat, jfloat);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Transform_transformPoint
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Transform_1transformPoint__JJJ
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Transform_transformRect
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Transform_1transformRect
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Transform_combine
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Transform_1combine
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Transform_translate
 * Signature: (JFF)J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Transform_1translate__JFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Transform_translate
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Transform_1translate__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Transform_rotate
 * Signature: (JF)J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Transform_1rotate__JF
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Transform_rotate
 * Signature: (JFFF)J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Transform_1rotate__JFFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Transform_rotate
 * Signature: (JFJ)J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Transform_1rotate__JFJ
  (JNIEnv *, jclass, jlong, jfloat, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Transform_scale
 * Signature: (JFF)J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Transform_1scale__JFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Transform_scale
 * Signature: (JFFFF)J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Transform_1scale__JFFFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Transform_scale
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Transform_1scale__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Transform_scale
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Transform_1scale__JJJ
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    operator_mul__sf_Transform__sf_Transform
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_operator_1mul_1_1sf_1Transform_1_1sf_1Transform
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    operator_mul__sf_Transform__sf_Vector2f
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_operator_1mul_1_1sf_1Transform_1_1sf_1Vector2f
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    operator_eq__sf_Transform__sf_Transform
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_operator_1eq_1_1sf_1Transform_1_1sf_1Transform
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Transformable_sizeof
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Transformable_1sizeof
  (JNIEnv *, jclass);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Transformable_Transformable
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Transformable_1Transformable__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Transformable_Transformable
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Transformable_1Transformable__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Transformable_destructor
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Transformable_1destructor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Transformable_setPosition
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Transformable_1setPosition__JFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Transformable_setPosition
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Transformable_1setPosition__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Transformable_setRotation
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Transformable_1setRotation
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Transformable_setScale
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Transformable_1setScale__JFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Transformable_setScale
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Transformable_1setScale__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Transformable_setOrigin
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Transformable_1setOrigin__JFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Transformable_setOrigin
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Transformable_1setOrigin__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Transformable_getPosition
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Transformable_1getPosition
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Transformable_getRotation
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Transformable_1getRotation
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Transformable_getScale
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Transformable_1getScale
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Transformable_getOrigin
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Transformable_1getOrigin
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Transformable_move
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Transformable_1move__JFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Transformable_move
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Transformable_1move__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Transformable_rotate
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Transformable_1rotate
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Transformable_scale
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Transformable_1scale__JFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Transformable_scale
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Transformable_1scale__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Transformable_getTransform
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Transformable_1getTransform
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Transformable_getInverseTransform
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Transformable_1getInverseTransform
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Vertex_sizeof
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Vertex_1sizeof
  (JNIEnv *, jclass);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Vertex_position
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Vertex_1position
  (JNIEnv *, jclass);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Vertex_color
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Vertex_1color
  (JNIEnv *, jclass);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Vertex_texCoords
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Vertex_1texCoords
  (JNIEnv *, jclass);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_Vertex_Vertex
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1Vertex_1Vertex
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_VertexArray_sizeof
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1VertexArray_1sizeof
  (JNIEnv *, jclass);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_VertexArray_VertexArray
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1VertexArray_1VertexArray__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_VertexArray_VertexArray
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1VertexArray_1VertexArray__JIJ
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_VertexArray_destructor
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1VertexArray_1destructor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_VertexArray_getVertexCount
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1VertexArray_1getVertexCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_VertexArray_operator_index
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1VertexArray_1operator_1index
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_VertexArray_clear
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1VertexArray_1clear
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_VertexArray_resize
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1VertexArray_1resize
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_VertexArray_append
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1VertexArray_1append
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_VertexArray_setPrimitiveType
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1VertexArray_1setPrimitiveType
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_VertexArray_getPrimitiveType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1VertexArray_1getPrimitiveType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_VertexArray_getBounds
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1VertexArray_1getBounds
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_sfml_dev_graphics_sys_SFML_Graphics
 * Method:    sf_VertexArray_draw
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_graphics_sys_SFML_1Graphics_sf_1VertexArray_1draw
  (JNIEnv *, jclass, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
