/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sfml_dev_window_sys_SFML_Window */

#ifndef _Included_org_sfml_dev_window_sys_SFML_Window
#define _Included_org_sfml_dev_window_sys_SFML_Window
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_sfml_dev_window_sys_SFML_Window
 * Method:    sf_Clipboard_getString
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_window_sys_SFML_1Window_sf_1Clipboard_1getString
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_window_sys_SFML_Window
 * Method:    sf_Clipboard_setString
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_window_sys_SFML_1Window_sf_1Clipboard_1setString
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
