/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sfml_dev_system_sys_SFML_System */

#ifndef _Included_org_sfml_dev_system_sys_SFML_System
#define _Included_org_sfml_dev_system_sys_SFML_System
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_sfml_dev_system_sys_SFML_System
 * Method:    sf_Clock_sizeof
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_system_sys_SFML_1System_sf_1Clock_1sizeof
  (JNIEnv *, jclass);

/*
 * Class:     org_sfml_dev_system_sys_SFML_System
 * Method:    sf_Clock_Clock
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_system_sys_SFML_1System_sf_1Clock_1Clock__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_system_sys_SFML_System
 * Method:    sf_Clock_Clock
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_system_sys_SFML_1System_sf_1Clock_1Clock__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_sfml_dev_system_sys_SFML_System
 * Method:    sf_Clock_getElapsedTime
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_system_sys_SFML_1System_sf_1Clock_1getElapsedTime
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_system_sys_SFML_System
 * Method:    sf_Clock_restart
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_system_sys_SFML_1System_sf_1Clock_1restart
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_system_sys_SFML_System
 * Method:    sf_String_sizeof
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_system_sys_SFML_1System_sf_1String_1sizeof
  (JNIEnv *, jclass);

/*
 * Class:     org_sfml_dev_system_sys_SFML_System
 * Method:    sf_String_String
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_system_sys_SFML_1System_sf_1String_1String
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_system_sys_SFML_System
 * Method:    sf_String_destructor
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_system_sys_SFML_1System_sf_1String_1destructor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_system_sys_SFML_System
 * Method:    sf_String_fromUtf16
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_system_sys_SFML_1System_sf_1String_1fromUtf16
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_sfml_dev_system_sys_SFML_System
 * Method:    sf_String_toUtf16
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_system_sys_SFML_1System_sf_1String_1toUtf16
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_sfml_dev_system_sys_SFML_System
 * Method:    sf_Vector2i_sizeof
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_system_sys_SFML_1System_sf_1Vector2i_1sizeof
  (JNIEnv *, jclass);

/*
 * Class:     org_sfml_dev_system_sys_SFML_System
 * Method:    sf_Vector2i_Vector2i
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_system_sys_SFML_1System_sf_1Vector2i_1Vector2i
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_sfml_dev_system_sys_SFML_System
 * Method:    sf_Vector2i_getX
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_sfml_1dev_system_sys_SFML_1System_sf_1Vector2i_1getX
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_system_sys_SFML_System
 * Method:    sf_Vector2i_getY
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_sfml_1dev_system_sys_SFML_1System_sf_1Vector2i_1getY
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_system_sys_SFML_System
 * Method:    sf_Vector2u_sizeof
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_system_sys_SFML_1System_sf_1Vector2u_1sizeof
  (JNIEnv *, jclass);

/*
 * Class:     org_sfml_dev_system_sys_SFML_System
 * Method:    sf_Vector2u_Vector2u
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_system_sys_SFML_1System_sf_1Vector2u_1Vector2u
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_sfml_dev_system_sys_SFML_System
 * Method:    sf_Vector2u_getX
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_sfml_1dev_system_sys_SFML_1System_sf_1Vector2u_1getX
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_system_sys_SFML_System
 * Method:    sf_Vector2u_getY
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_sfml_1dev_system_sys_SFML_1System_sf_1Vector2u_1getY
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_system_sys_SFML_System
 * Method:    sf_Vector2f_sizeof
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_system_sys_SFML_1System_sf_1Vector2f_1sizeof
  (JNIEnv *, jclass);

/*
 * Class:     org_sfml_dev_system_sys_SFML_System
 * Method:    sf_Vector2f_Vector2f
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_system_sys_SFML_1System_sf_1Vector2f_1Vector2f
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     org_sfml_dev_system_sys_SFML_System
 * Method:    sf_Vector2f_getX
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_sfml_1dev_system_sys_SFML_1System_sf_1Vector2f_1getX
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_system_sys_SFML_System
 * Method:    sf_Vector2f_getY
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_sfml_1dev_system_sys_SFML_1System_sf_1Vector2f_1getY
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_system_sys_SFML_System
 * Method:    sf_Vector3f_sizeof
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_system_sys_SFML_1System_sf_1Vector3f_1sizeof
  (JNIEnv *, jclass);

/*
 * Class:     org_sfml_dev_system_sys_SFML_System
 * Method:    sf_Vector3f_getX
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_sfml_1dev_system_sys_SFML_1System_sf_1Vector3f_1getX
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_system_sys_SFML_System
 * Method:    sf_Vector3f_getY
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_sfml_1dev_system_sys_SFML_1System_sf_1Vector3f_1getY
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_system_sys_SFML_System
 * Method:    sf_Vector3f_getZ
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_sfml_1dev_system_sys_SFML_1System_sf_1Vector3f_1getZ
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
