/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sfml_dev_system_sys_SFML_System */

#ifndef _Included_org_sfml_dev_system_sys_SFML_System
#define _Included_org_sfml_dev_system_sys_SFML_System
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_sfml_dev_system_sys_SFML_System
 * Method:    sf_Clock_sizeof
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_system_sys_SFML_1System_sf_1Clock_1sizeof
  (JNIEnv *, jclass);

/*
 * Class:     org_sfml_dev_system_sys_SFML_System
 * Method:    sf_Clock_Clock
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_system_sys_SFML_1System_sf_1Clock_1Clock
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_system_sys_SFML_System
 * Method:    sf_Clock_getElapsedTime
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_system_sys_SFML_1System_sf_1Clock_1getElapsedTime
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_system_sys_SFML_System
 * Method:    sf_Clock_restart
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_system_sys_SFML_1System_sf_1Clock_1restart
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_system_sys_SFML_System
 * Method:    sf_String_sizeof
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_system_sys_SFML_1System_sf_1String_1sizeof
  (JNIEnv *, jclass);

/*
 * Class:     org_sfml_dev_system_sys_SFML_System
 * Method:    sf_String_String
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_system_sys_SFML_1System_sf_1String_1String
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_system_sys_SFML_System
 * Method:    sf_String_destructor
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_system_sys_SFML_1System_sf_1String_1destructor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_system_sys_SFML_System
 * Method:    sf_String_fromUtf16
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_system_sys_SFML_1System_sf_1String_1fromUtf16
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_sfml_dev_system_sys_SFML_System
 * Method:    sf_String_toUtf16
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_system_sys_SFML_1System_sf_1String_1toUtf16
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
