/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sfml_dev_system_sys_string */

#ifndef _Included_org_sfml_dev_system_sys_string
#define _Included_org_sfml_dev_system_sys_string
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_sfml_dev_system_sys_string
 * Method:    std_u16string_sizeof
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_system_sys_string_std_1u16string_1sizeof
  (JNIEnv *, jclass);

/*
 * Class:     org_sfml_dev_system_sys_string
 * Method:    std_u16string_destructor
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_system_sys_string_std_1u16string_1destructor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_system_sys_string
 * Method:    std_u16string_data
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_system_sys_string_std_1u16string_1data
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_system_sys_string
 * Method:    std_u16string_size
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_system_sys_string_std_1u16string_1size
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
