/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sfml_dev_system_sys_System */

#ifndef _Included_org_sfml_dev_system_sys_System
#define _Included_org_sfml_dev_system_sys_System
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_sfml_dev_system_sys_System
 * Method:    sf_Clock_Clock
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_sfml_1dev_system_sys_System_sf_1Clock_1Clock
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_system_sys_System
 * Method:    sf_Clock_getElapsedTime
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_system_sys_System_sf_1Clock_1getElapsedTime
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_system_sys_System
 * Method:    sf_Clock_restart
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_system_sys_System_sf_1Clock_1restart
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
