/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sfml_dev_system_sys_vector */

#ifndef _Included_org_sfml_dev_system_sys_vector
#define _Included_org_sfml_dev_system_sys_vector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_sfml_dev_system_sys_vector
 * Method:    std_vector_sf_VideoMode_begin
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_system_sys_vector_std_1vector_1sf_1VideoMode_1begin
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_sfml_dev_system_sys_vector
 * Method:    std_vector_sf_VideoMode_end
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_sfml_1dev_system_sys_vector_std_1vector_1sf_1VideoMode_1end
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
